package fr.naruse.towerdefense.unit.level;

public enum LevelAttribute {

    MAX_HEALTH,
    HEAL_FACTOR,

    WEAPON_BULLET_AMOUNT,
    WEAPON_BULLET_DAMAGE,
    WEAPON_BULLET_SPEED,
    WEAPON_VIEW_RADIUS,

    GOLD_DIGGER_PER_SECOND,

    HARVESTER_HARVEST_LINES,
    HARVESTER_DISTANCE_FROM_RESOURCE,
    HARVESTER_HARVESTED_PER_SECOND,
    HARVESTER_ITEM_SPEED,
}
